#!/bin/sh

"$TESTDIR/hghave" git || exit 80

start_daemon() {
 git daemon --base-path="`pwd`"\
  --listen=localhost \
  --export-all \
  --pid-file=gitdaemon.pid \
  --detach --reuseaddr
 sleep 0.5
 kill -0 `cat gitdaemon.pid`
}

mkdir gitrepo
cd gitrepo
git init -q
git fast-import --quiet < "$TESTDIR/git-sample-repo"

cd ..
start_daemon || exit 80

hg gclone git://localhost/gitrepo hgrepo
cd hgrepo
hg log

cd ..
kill `cat gitdaemon.pid`
