#!/bin/sh

"$TESTDIR/hghave" git || exit 80

hg init
git init -q

echo alpha > alpha
git add alpha
git commit -qm 'add alpha'

echo beta > beta
git add beta
git commit -qm 'add beta'

mkdir foo
echo blah > foo/bar
git add foo
git commit -qm 'add foo'

git rm alpha
git commit -qm 'remove alpha'

git rm foo/bar
git commit -qm 'remove foo/bar'

echo % final manifest in git is just beta
git ls-files

hg gimport
hg log

echo
echo % make sure alpha is not in this manifest
hg manifest -r 3

echo
echo % make sure that only beta is in the manifest
hg manifest -r tip
