#!/bin/sh

"$TESTDIR/hghave" git || exit 80

echo "[extensions]" >> $HGRCPATH
echo "bookmarks = " >> $HGRCPATH

hg init
git init -q

mkdir d1
touch d1/f1 d1/f2
git add d1/f1 d1/f2
git commit -qm initial

mkdir d2
git mv d1/f2 d2/f2
git commit -qm rename

hg gimport
hg log -r tip --template 'adds: {file_adds}\ndels: {file_dels}\n'
