#!/bin/sh

"$TESTDIR/hghave" git || exit 80

hg init
git init -q

git commit --allow-empty -qm empty

echo % original HEAD
git rev-list -n 1 HEAD

hg gimport
hg log -r tip --template 'files: {files}\n'

hg gclear
hg gexport

echo % exported HEAD
git rev-list -n 1 HEAD
